# Generated by Django 2.2.5 on 2019-10-01 03:15

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tacocreate', '0003_auto_20190930_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taco',
            name='seasoning_choice',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Mahi Mahi Rub', 'Mahi Mahi Rub'), ('Packaged Seasonings', 'Packaged Seasonings'), ('Quick and Dirty Spice Mix', 'Quick and Dirty Spice Mix'), ('Sriracha Salt', 'Sriracha Salt'), ('Universal Taco Seasoning', 'Universal Taco Seasoning'), ('Zaatar', 'Zaatar')], max_length=100),
        ),
    ]
