# Generated by Django 2.2.5 on 2019-10-01 03:20

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tacocreate', '0004_auto_20190930_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taco',
            name='condiment_choice',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Pickled Vegetables', 'Pickled Vegetables'), ('Baja White Sauce', 'Baja White Sauce'), ('Beet Salsa', 'Beet Salsa'), ('Chipotlé Sauce', 'Chipotlé Sauce'), ('Guacamole', 'Guacamole'), ('Mango Avocado Salsa', 'Mango Avocado Salsa'), ('Phoning it in Pico de Gallo', 'Phoning it in Pico de Gallo'), ('Pickled Red Onions', 'Pickled Red Onions'), ('Salsa Sauce', 'Salsa Sauce'), ('Simple Salsa Verde', 'Simple Salsa Verde'), ('Roasted Tomatillo and Mushroom Sauce', 'Roasted Tomatillo and Mushroom Sauce'), ('Black Olives', 'Black Olives'), ('Salsa de chile de árbol', 'Salsa de chile de árbol'), ('Cashew Cheeze', 'Cashew Cheeze'), ('Guacamole (Simple)', 'Guacamole (Simple)'), ('Sour Cream', 'Sour Cream'), ('Cranberry Salsa', 'Cranberry Salsa'), ('Garlic Lime Sauce', 'Garlic Lime Sauce'), ('Mango Lime Salsa', 'Mango Lime Salsa'), ('Salsa de Aguacate', 'Salsa de Aguacate')], max_length=100),
        ),
        migrations.AlterField(
            model_name='taco',
            name='mixin_choice',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Corn Salad', 'Corn Salad'), ('Drunken Green Beans', 'Drunken Green Beans'), ('Sweet Potato and Apple Hash', 'Sweet Potato and Apple Hash'), ('Veggies for Fish Tacos', 'Veggies for Fish Tacos'), ('Potato Hash', 'Potato Hash'), ('Cheese (Traditional; US)', 'Cheese (Traditional; US)'), ('Lettuce (Traditional; US)', 'Lettuce (Traditional; US)'), ('Tomatoes (Traditional; US)', 'Tomatoes (Traditional; US)'), ('Traditional Taco Mixins', 'Traditional Taco Mixins'), ('Green Chile Cabbage Salad', 'Green Chile Cabbage Salad')], max_length=100),
        ),
    ]
