# Generated by Django 2.2.5 on 2019-10-01 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tacocreate', '0005_auto_20190930_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taco',
            name='seasoning_choice',
            field=models.CharField(choices=[('Mahi Mahi Rub', 'Mahi Mahi Rub'), ('Packaged Seasonings', 'Packaged Seasonings'), ('Quick and Dirty Spice Mix', 'Quick and Dirty Spice Mix'), ('Sriracha Salt', 'Sriracha Salt'), ('Universal Taco Seasoning', 'Universal Taco Seasoning'), ('Zaatar', 'Zaatar')], max_length=100),
        ),
    ]
